package constants;

public enum Game {
    CAROUSEL, MARRY_GO_ROUND, BALLOON_DOG, SPRING_SWING_CAR,
    BOUNCY_CASTLE, WATER_SLIDE, BUMPER, BOXING_MACHINE,
    ROLLER_COASTER, FERRIS_WHEEL, PIRATE_SHIP, SPRING_SWING
}
